### ISSUE TITLE
onClick does not work, but onMouseOver does

### ISSUE THREAD

**Issue by Torniojaws** [clauderic/react-sortable-hoc#206] opened 2017-05-24 09:49 UTC
I noticed this behaviour when implementing a "Delete" button inside each sortable element.

```
class Someclass extends React.component {
    // constructor and some unrelated functions...
    
    removeItem(e) {
        e.preventDefault();
        console.log("User clicked on X");
    }
    render() {
        return (
            <div className="reorder">
                <SortableList
                    items={this.state.items}
                    onSortEnd={this.onSortEnd}
                    axis={"xy"}
                    removeItem={this.removeItem}
                />
            </div>
        );
    }
}
```

Then the sortable things on top of the file:
```
const SortableItem = SortableElement(({value, removeItem}) =>
    <li className="list-group-item reorder-box">
        {value} <span className="glyphicon glyphicon-remove" onClick={removeItem}></span>
    </li>
);

const SortableList = SortableContainer(({items, removeItem}) => {
    return (
        <ul className="list-inline">
            {items.map((value, index) => (
                <SortableItem key={`item-${index}`} index={index} value={value} removeItem={removeItem}/>
            ))}
        </ul>
    );
});
```

Now, inside the ``<span>`` of ``SortableItem``, I have ``onClick={removeItem}`` in the above example. It does not show anything in the console when I click on it. However, if I change it to ``onMouseOver={removeItem}``, then it does show the expected ``User clicked on X`` message in console.

However, I want it to use ``onClick`` - is it possible to use this way?

**Comment by Torniojaws** [comment] 2017-05-24 10:38
Ah of course, the onClick event is already used by react-sortable-hoc. So anything within it cannot use onClick. Hmm, would be good if that was possible though.

**Comment by clauderic** [comment] 2017-05-24 13:38
Duplicate of #111 

Currently, there are a number of different approaches already available to get around this:

- You can use a SortableHandle
- You can also use the distance prop to set a minimum distance to be dragged before sorting is triggered (for instance, you could set a distance of 1px like so: distance={1})
- You can also use the pressDelay prop to set a delay before sorting is triggered.

I believe these should be sufficient to cover most use cases, but I'm open to suggestions if you guys have other ideas.

**Closed by clauderic** 2017-05-24 13:38 UTC

**Comment by akash123srm** [comment] 2019-12-11 15:11
for my specific use case I used onPointerDown event  to remove items from the list which worked.

**Comment by rod-taxpayer** [comment] 2025-10-12 16:17
@clauderic https://reactjs-dusty.github.io/-a-JB6vGahkRqTnlDbJ2mRpxEhEs6sTW/
