### ISSUE TITLE
Sort multiple items at once

### ISSUE THREAD

**Issue by bbosiljcic** [clauderic/react-sortable-hoc#318] opened 2017-11-24 12:19 UTC
I was wondering if there is currently a way to make multiple items sortable at once. One could use a modifier key to select multiple items and then just drag them whereever.

**Comment by mohsom** [comment] 2017-12-06 07:29
Encountered the same problem, need to implement dnd for selected items it the list.
Any suggestions?

**Comment by sbr464** [comment] 2017-12-24 20:04
check out this repo,  cmd + click selects multiple items

https://github.com/reactual/react-multi-sortable-hoc-demo

**Comment by clauderic** [comment] 2019-03-13 05:47
Duplicate of #296

**Closed by clauderic** 2019-03-13 05:47 UTC

**Comment by clauderic** [comment] 2019-03-18 01:47
This is already possible without any changes to the core of `react-sortable-hoc`, and I've now added an example for how to do it, see: https://github.com/clauderic/react-sortable-hoc/tree/master/src/.stories/grouping-items

<img src="https://user-images.githubusercontent.com/1416436/54495093-437d2200-48b7-11e9-885b-05e64c554615.gif" width="400" />

**Comment by alina-lapina** [comment] 2019-10-14 09:56
> This is already possible without any changes to the core of `react-sortable-hoc`, and I've now added an example for how to do it, see: https://github.com/clauderic/react-sortable-hoc/tree/master/src/.stories/grouping-items
> 
> <img alt="" width="400" src="https://user-images.githubusercontent.com/1416436/54495093-437d2200-48b7-11e9-885b-05e64c554615.gif">

Hi, cannot find a demo for GroupedItems in the repository. Can you help me with it, please?

**Comment by mtztkt** [comment] 2020-10-05 12:19
@clauderic add a demo please
