### ISSUE TITLE
No animation in IE11 

### ISSUE THREAD

**Issue by ochervak** [clauderic/react-sortable-hoc#17] opened 2016-06-21 09:48 UTC
On chrome example works ultra smooth and fast, however in IE11 there is NO animations at all. How can i eliminate this ?

**Comment by clauderic** [comment] 2016-06-21 09:50
This is a bug, I'm fixing it as we speak. Also, duplicate of #7

**Comment by ochervak** [comment] 2016-06-21 09:51
@clauderic thanks! can i help you with it ?

**Closed by clauderic** 2016-06-21 09:50 UTC

**Comment by clauderic** [comment] 2016-06-21 09:51
Sure! Feel free to chime in the PR for it here: https://github.com/clauderic/react-sortable-hoc/pull/10
