### ISSUE TITLE
Item disappearing when dragging

### ISSUE THREAD

**Issue by jeffbonasso** [clauderic/react-sortable-hoc#129] opened 2017-01-28 12:28 UTC
I am trying to use where my sortable list is in a modal. I tried react-bootstrap modal and react-modal-dialog libraries and with both my item disappears when dragging. You mention in your readme about potential of item disappearing. Is there an easy solution if this occurs?

**Comment by clauderic** [comment] 2017-01-28 19:41
Hey @jeffbonasso, this is a duplicate of https://github.com/clauderic/react-sortable-hoc/issues/87.

Short answer: It's a z-index issue

**Closed by clauderic** 2017-01-28 19:41 UTC

**Comment by jeffbonasso** [comment] 2017-01-28 20:04
Awesome. Set a higher z-index on SortableElement and worked like a charm. Thanks!
