### ISSUE TITLE
Incorrect drag offsets when a parent element has a translation applied

### ISSUE THREAD

**Issue by alex-greff** [clauderic/react-sortable-hoc#505] opened 2019-02-26 19:52 UTC
Hi,
I have found an issue with the offset drag calculation when a parent element of the _helperContainer_ ref has a transform applied to it.

**Issue Reproduction:** https://codesandbox.io/s/lpp1q7jjwm

I have also seen a similar issue that was [found](https://github.com/clauderic/react-sortable-hoc/issues/455) but instead with rotation and there does not seem to be a solution for it yet (other than manually overriding the affected styles).

Is there any ETA on if/when we can expect these fix(es) to be implemented?

Thanks,
Alex

**Comment by clauderic** [comment] 2019-03-13 05:24
Duplicate of #386, please contribute to that issue

**Closed by clauderic** 2019-03-13 05:24 UTC

**Comment by vikas-0** [comment] 2021-04-15 11:31
@alex-greff did you find any workaround for this?
