### ISSUE TITLE
Sometimes doesn't work in Chrome

### ISSUE THREAD

**Issue by nbrady-techempower** [clauderic/react-sortable-hoc#18] opened 2016-06-21 15:26 UTC
When first loaded in a new Chrome window, dragging works fine, then for some reason it just stops working in every tab on that window. If I open a new window it works again. Both my code and the examples stop working with no indication to a problem in the console.

**Comment by clauderic** [comment] 2016-06-21 15:38
Are you intermittently using the Chrome touch event simulator by any chance? I'm issuing a fix for a similar issue and wondering if this is related.

**Comment by nbrady-techempower** [comment] 2016-06-21 16:31
I am not. I'm going through some extensions but can't find a correlation.

**Comment by dmiller9911** [comment] 2016-06-21 18:48
I am seeing this as well, and looks to be due to this:  

https://bugs.chromium.org/p/chromium/issues/detail?id=161464

I tracked the events, and I am getting a mousemove event right after mouse down which is causing it to clear the timeout since I have a pressDelay set.

**Comment by clauderic** [comment] 2016-06-22 13:46
Hmm, I see. From the looks of it this is a Windows only issue? I suppose I could check if `e.type == 'mousemove' || e.type = 'touchmove'` before clearing the `pressDelay` timeout

**Comment by clauderic** [comment] 2016-06-22 14:40
Ah derp but that still wouldn't help... Hmm. @nbrady-techempower are you using `pressDelay` as well?

**Comment by nbrady-techempower** [comment] 2016-06-22 15:45
@clauderic No I'm not using `pressDelay` or any other props. Pretty much exactly as the README example.

**Comment by happycamper** [comment] 2016-06-22 23:20
@clauderic First, great stuff! But I can also confirm that after your last push early today that I no longer have a working README example or the code that i built yesterday. Seeing same issues as @nbrady-techempower

**Comment by clauderic** [comment] 2016-06-22 23:25
Hey @happycamper, @nbrady-techempower I'm unable to replicate this issue. Can you guys share some details on what OS you're using, version of chrome, whether you're on a laptop that has a touchscreen, and anything you can think of that could help find what's causing this? Might be easier to chat about this on Gitter https://gitter.im/clauderic/react-sortable-hoc

**Comment by nbrady-techempower** [comment] 2016-06-24 18:37
@clauderic I'm updated to 0.0.3 and can no longer replicate the issue. Thanks for your efforts with this project! I hope to be using it in production soon. I'll mark this as closed for now.

**Comment by dsvgit** [comment] 2016-11-30 09:42
I can replicate it. I think it isn't resolved

**Comment by clauderic** [comment] 2016-11-30 13:59
@dsvgit would you mind providing more details?

**Comment by arackaf** [comment] 2016-11-30 16:23
Replicated - chrome only.  Windows 10 version 54.0.2840.99.  The messed up part is, rebooting Chrome (or opening a fresh window) fixes it.

I'm thinking this is a Chrome bug?  Maybe?  

Does anyone have any idea what the problem *could* be?

**Comment by arackaf** [comment] 2016-11-30 16:33
And, annoyingly, it looks like this reliably reproduces when I open Chrome normally, with my other 5 auto tabs open, then browse to your demo page.

But a new single stand-alone window in Chrome has everything working fine.  

This is just bizarre.

**Comment by dsvgit** [comment] 2016-12-05 10:14
@clauderic  when it doesn't work I put breakpoint, for example, in function handleStart and then it works. If remove it doesn't.

**Comment by dsvgit** [comment] 2016-12-05 11:41
Something wrong with timeout in handleStart function - it doesn't work.
If I do these changes it works:
```javascript
if (!distance) {
	return _this.handlePress(e);
	//_this.pressTimer = setTimeout(function () {
	//	return _this.handlePress(e);
	//}, _this.props.pressDelay);
}
```

**Comment by clauderic** [comment] 2016-12-05 15:43
Hey @dsvgit, just merged #71 to that effect

**Comment by dsvgit** [comment] 2016-12-05 16:16
@clauderic are you going to update npm package?

**Comment by dsvgit** [comment] 2016-12-06 05:36
Now it works when pressDelay={0} and doesn't when it great than 0

**Comment by dsvgit** [comment] 2016-12-06 05:52
Problem is that
handleMove do that on click:
```javascript
_this.manager.active = null;
```
before that in handlePress:
```javascript
var active = _this.manager.getActive();
```

**Comment by arackaf** [comment] 2017-02-13 15:37
@clauderic this was fixed long ago, wasn't it?  Any reason the case is still open?  

Someone just sent me this, mentioning that it was still open, and asking if that bug was closed.  -- just fyi.

**Comment by jamespero** [comment] 2017-02-13 17:25
FYI I'm seeing this today when I have pressDelay set. Opening a new window and it works in the new window.

**Comment by alvinxiao** [comment] 2017-03-04 00:50
Chiming in to add that I see the problem whether I have pressDelay set or not. Opening a new window fixes the issue but only temporarily until it happens again

**Comment by clauderic** [comment] 2017-03-09 05:10
Hey @jamespero, @alvinxiao, 

What you experienced was actually a misdiagnosed issue. I _believe_ it was actually due to the fact that the `pressDelay` prop was not fault tolerant, meaning if you moved the mouse even by one pixel, it would cancel the press event. 

I can see how that could easily be a problem on trackpads or with a sensitive mouse, and have added a `pressThreshold` prop to make it more fault tolerant. The default value is set to `5` pixels. See #159 for more details.

**Closed by clauderic** 2017-03-09 05:10 UTC
