### ISSUE TITLE
Compatibility issue with semantic-ui-react

### ISSUE THREAD

**Issue by vineet89** [clauderic/react-sortable-hoc#583] opened 2019-08-21 04:49 UTC
I spent the past few hours debugging and fixing odd behaviour of react-sortable-hoc when used in conjunction with semantic-ui-react. This should save time whoever tries this next.

TL;DR Always use disableAutoScroll prop when using with semantic-ui-react

The list items snap back to original position and overlap with helper thus making sorting unachievable. The reason is auto scroll timer keeps firing and adjusting sortableOffset.top value when drag is active (even if it is not moving). Basically react-sortable-hoc falls into a vicious loop when drag is active.

**Comment by clauderic** [comment] 2019-08-21 18:56
Would you mind putting together a CodeSandbox replicating the issue?

**Comment by clauderic** [comment] 2019-08-21 18:57
Closing this issue for now until you can show me what the issue is.

**Closed by clauderic** 2019-08-21 18:57 UTC
Labels: more info needed

**Comment by RadoRado** [comment] 2019-10-07 16:39
@clauderic :wave: 

Thanks for the great library. Works like a charm, but I witnessed some problems / glitching when combined with Semantic UI.

Here's a sandbox with the problem reproduced: https://codesandbox.io/s/hungry-bhabha-14ovk

Try dragging from the last list. It glitches & does not behave properly.

The problem occurs when there are more than 1 list on a single page.

**Comment by RadoRado** [comment] 2019-10-07 16:41
Also, can confirm that adding `disableAutoScroll={true}` fixes the issue (@vineet89)

```
<SortableContainer disableAutoScroll={true}>
    ....
```

**Comment by RadoRado** [comment] 2019-10-07 16:47
Actually, sorry, `disableAutoScroll` does not fix the issue. I've updated the sandbox from above :+1:

**Comment by RadoRado** [comment] 2019-10-07 16:59
Okay, final one from me, setting `useWindowAsScrollContainer={true}` on the container actually fixes the issue.

Haven't updated the sandbox - https://codesandbox.io/s/hungry-bhabha-14ovk - so people can see the actual problem :raised_hands:
