### ISSUE TITLE
Animate to new position on release

### ISSUE THREAD

**Issue by rihok** [clauderic/react-sortable-hoc#345] opened 2018-02-25 13:27 UTC
One feature that seems to be missing from this library is animating the item to its new position. Currently, the item just instantly appears in the correct position after release. This feels very unnatural given that the rest of the list is animating quite nicely.

**Comment by RonnyO** [comment] 2018-03-28 10:59
See https://github.com/clauderic/react-sortable-hoc/issues/217 and the open PR there.

**Comment by clauderic** [comment] 2019-03-13 05:44
Closing, duplicate of #217

**Closed by clauderic** 2019-03-13 05:45 UTC
