### ISSUE TITLE
Flex & CSS Styling on Drag & Drop

### ISSUE THREAD

**Issue by botoxparty** [clauderic/react-sortable-hoc#464] opened 2019-01-04 03:04 UTC
Hey,

I seem to be having an issue where i have a container that is being dragged loses it's flex property.

This is a basic example of the setup. All the items in "playlist-items" unflex when the "row" is being sorted.

```
.row {
   width: 100%;
}

.playlist-items {
    width: 100%;
    display: flex;
}

<div className="row">
    <h2>My playlist</h2>
    <div className="playlist-items>
         <img>
         <img>
         <img>
         <img>
         <img>
         <img>
    </div>
</div>
```

**Comment by botoxparty** [comment] 2019-01-04 03:10
I should also mention that if i make it `<div className="playlist-items" style="display: flex">` then it corrects this.

**Comment by clauderic** [comment] 2019-01-08 16:42
Closing this unless you can provide a CodeSandbox reproducing the issue for me to look at. You can also try asking on StackOverflow, as Github is mostly intended for reporting issues with a library.

**Closed by clauderic** 2019-01-08 16:42 UTC

**Comment by zheNeng** [comment] 2019-04-10 09:44
可能是因为样式嵌套? 
库会把原来的ele隐藏，在Body上挂载一个临时的ele。
而这个临时的ele，因为脱离了原先的css嵌套结构，丢失了样式

**Comment by solankivj94** [comment] 2020-04-16 04:14
> Probably because the style is nested? The
> library will hide the original ele and mount a temporary ele on the Body.
> And this temporary ele lost its style because it broke away from the original CSS nesting structure

Thanks for information, i am experiencing same issue, do you know how to fix it ?
