### ISSUE TITLE
transition for dropping element to a new position

### ISSUE THREAD

**Issue by Rezaaa** [clauderic/react-sortable-hoc#199] opened 2017-04-29 12:31 UTC
It would be good if you add some transition for dropping element to a new position.

**Comment by clauderic** [comment] 2017-04-29 13:34
Duplicate of #63.

In short, I'd be more than happy to look at a PR that would implement this kind of functionality, but it isn't something I have enough bandwidth to work on myself.

**Closed by clauderic** 2017-04-29 13:34 UTC

**Comment by davidetruffo** [comment] 2018-08-16 09:56
@clauderic what about this? #308 
It looks like it addresses this issue :)

(Thanks for the great work, btw! Kudos!)

**Comment by lmenus** [comment] 2018-08-30 14:35
+1 @clauderic
