### ISSUE TITLE
Can't use two SortableLists in same view: Uncaught TypeError: Cannot read property 'collection' of null

### ISSUE THREAD

**Issue by ricardometring** [clauderic/react-sortable-hoc#8] opened 2016-06-12 07:19 UTC
When trying to add two SortableLists in the same view, I'm getting this error while sorting an element:

```
Uncaught TypeError: Cannot read property 'collection' of null
```

I tried with the sample code in the readme, and got the same error.

**Comment by clauderic** [comment] 2016-06-12 07:29
Yeah, this is a duplicate of #2. It's a fairly easy fix, but I can't take care of it for another week. Check out the conversations that happened on Gitter, there are several proposed workarounds

**Closed by clauderic** 2016-06-12 07:29 UTC
