### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by johnkorzhuk** [clauderic/react-sortable-hoc#92] opened 2016-11-20 23:03 UTC
I'm fairly new to the Github community, so if it's considered bad manners to post questions under issues or if there's a better way to ask a developer a question, please let me know. I feel awkward opening up an issue just to ask you a question. 

[Here's](https://gyazo.com/51919e794b851a4dcafd276a16147035) a simple to-do app I'm working on to get a better grasp of React. I'd like to be able to move the tasks within the **To do:** component as well as move them into the **Completed:** component, in turn changing their state to completed: true. Is this possible within sortable-hoc?

Also, I'm loving this so far. I tried my hand at React DnD, but failed pretty hard. I think I need a better grasp of flux architecture. react-sortable-hoc is far more intuitive for me. Thanks!

**Comment by clauderic** [comment] 2016-11-21 15:09
Hey @johnkorzhuk, 

This kind of request comes up a lot (#93, #3). 

In short, no, this is currently not something that is supported, though it is on the roadmap. 

Going to close this one out as it is a duplicate of #3. If this is something you would like to contribute to, please chime in on #3, all PRs are welcome :)

If you have more questions, don't hesitate to come chat on [Gitter](https://gitter.im/clauderic/react-sortable-hoc)

**Closed by clauderic** 2016-11-21 15:09 UTC
