### ISSUE TITLE
Cannot read property 'top' of undefined

### ISSUE THREAD

**Issue by george-norris-salesforce** [clauderic/react-sortable-hoc#305] opened 2017-11-06 21:18 UTC
https://codepen.io/stoplion/pen/QMzpVL?editors=0010

Each item has unique client id. When adding a new item, sorting the items causes error.
Using client id because in our situation, we can't depend on any other property of item being unique.

**Comment by faboulaws** [comment] 2018-01-09 12:28
+1

**Comment by schnubor** [comment] 2018-04-05 07:37
+1, having the same issue although using unique keys as described here https://github.com/clauderic/react-sortable-hoc/issues/270

**Comment by arbaaz** [comment] 2018-04-17 07:43
+1

**Comment by webamon** [comment] 2018-07-11 13:49
+1

**Comment by yueshuiniao** [comment] 2018-07-16 02:43
I try set 'index' and 'key' different value, it worked

**Comment by Thomas101** [comment] 2018-07-16 15:10
Hey, we've been seeing this with our project. After a lot of digging, we found that passing a custom component to `SortableElement` was the cause...

```js
const SortableItem = SortableElement((props) => {
  return (<MySortableItem {...props} />)
})
```

...rather than doing this, we wrapped our custom component in a native dom element and it seems to have fixed the issue...

```js
const SortableItem = SortableElement((props) => {
  return (
    <div>
      <MySortableItem {...props} />
    </div>
  )
})
```

### More info...

Digging through the react-sortable-hoc code, it looks like when a SortableElement is created it uses `ReactDom.findDOMNode` to grab the dom node and store it in a list of sortable elements. This is fine, however if a custom component has a dramatic re-render call which changes the root dom node it orphans the node out the dom and leaks it. For example...

```js
class MyComponent extends React.Component {
  render () {
    if (this.state.something) {
      return (<div>{...}</div>)
    } else {
      return (<li>{...}</li>)
    }
  }
}
```

(@george-norris-salesforce I see your example does this). When it does this, it generates the `Cannot read property` value when trying to calculate `edgeOffset` because the function bombs out failing to find the parent node.

Hope it helps someone else :)

**Comment by clauderic** [comment] 2019-03-18 03:27
Closing this issue for now, this will be solved in a future release with ref forwarding, as `findDOMNode` will eventually be deprecated from future versions of React

**Closed by clauderic** 2019-03-18 03:27 UTC

**Comment by panlina** [comment] 2020-02-24 14:55
@Thomas101 's answer saved my day. This issue still exists as of now. Is there any plan to fix it? @clauderic

**Comment by d0ublezer0** [comment] 2022-06-30 07:08
Problem still exist in release 2.0.0
